/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#2563eb',
          soft: '#eff4ff',
        },
        accent: '#0d9488',
        surface: '#ffffff',
        page: '#f5f7f9',
        desk: '#eceff3',
        ink: {
          DEFAULT: '#0f172a',
          2: '#334155',
          3: '#475569',
        },
        nav: '#5b6779',
        muted: {
          DEFAULT: '#64748b',
          2: '#94a3b8',
        },
        faint: '#b4bdc8',
        'table-header': '#8a95a3',
        line: {
          DEFAULT: '#e9edf2',
          soft: '#eef2f6',
        },
        'row-line': '#f1f4f7',
        'input-line': '#d8dee6',
        chip: '#f1f4f7',
        track: '#eef2f7',
        'table-head': '#f8fafc',
        'alt-row': '#fafbfc',
        status: {
          ok: {
            DEFAULT: '#16a34a',
            bg: '#e9f6ef',
            text: '#15803d',
          },
          busy: {
            DEFAULT: '#dc2626',
            bg: '#fde9e9',
            text: '#b91c1c',
          },
          warn: {
            DEFAULT: '#f59e0b',
            bg: '#fdf4e0',
            text: '#b45309',
          },
        },
        dark: {
          surface: '#1b222c',
          page: '#12171e',
          body: '#0c1116',
          ink: '#f1f5f9',
          'ink-2': '#d7dee7',
          'ink-3': '#b9c4d0',
          nav: '#9aa7b5',
          muted: '#94a3b8',
          'muted-2': '#7e8b99',
          faint: '#5c6875',
          line: '#2a3341',
          'line-soft': '#252e3a',
          'row-line': '#232c37',
          'input-line': '#3a4655',
          chip: '#29323e',
          track: '#2a333f',
          head: '#202834',
          'alt-row': '#1f2731',
        },
      },
      fontFamily: {
        'heading': ['PlusJakartaSans_700Bold', 'Plus Jakarta Sans', 'sans-serif'],
        'heading-medium': ['PlusJakartaSans_600SemiBold', 'Plus Jakarta Sans', 'sans-serif'],
        'heading-extra': ['PlusJakartaSans_800ExtraBold', 'Plus Jakarta Sans', 'sans-serif'],
        'body': ['Inter_400Regular', 'Inter', 'sans-serif'],
        'body-medium': ['Inter_500Medium', 'Inter', 'sans-serif'],
        'body-semibold': ['Inter_600SemiBold', 'Inter', 'sans-serif'],
        'body-bold': ['Inter_700Bold', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'page-title': ['19px', { lineHeight: '1.3', fontWeight: '700' }],
        'hero': ['40px', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.02em' }],
        'stat': ['30px', { lineHeight: '1.2', fontWeight: '700' }],
        'card-title': ['14px', { lineHeight: '1.4', fontWeight: '700' }],
        'body': ['14px', { lineHeight: '1.5' }],
        'body-sm': ['13.5px', { lineHeight: '1.5' }],
        'label': ['12.5px', { lineHeight: '1.4', fontWeight: '600' }],
        'table-header': ['11.5px', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '0.05em' }],
        'caption': ['12px', { lineHeight: '1.4' }],
        'caption-sm': ['11px', { lineHeight: '1.3' }],
      },
      borderRadius: {
        'card': '14px',
        'button': '10px',
        'input': '10px',
        'modal': '16px',
        'pill': '9999px',
      },
      boxShadow: {
        'card': '0 2px 8px rgba(15, 23, 42, 0.04)',
        'button-primary': '0 2px 6px rgba(37, 99, 235, 0.3)',
        'modal': '0 24px 60px rgba(15, 23, 42, 0.3)',
        'login-card': '0 10px 30px rgba(15, 23, 42, 0.06)',
      },
      spacing: {
        'sidebar': '228px',
        'header': '64px',
      },
    },
  },
  plugins: [],
};
